### ISSUE TITLE
[1.4] Issues with OPF and OPF Dashboard

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#399] opened 2019-03-22 07:58 UTC
Dashboard
- Upload of plugin filters is not possible, the upload field is hidden immediately after clicking on "Upload Filter (Plugin)"
- success message and overlay after upload (forcing upload dialogue to be displayed by changig the tool.htt file) does not disappear when clicking on OK or the X button

Frontend
- several lines of code are inserted 2 times into the < head >

**Comment by mrbaseman** [comment] 2019-03-22 10:58
probably this is caused because I::doFilter($content) is executed once for the Auto Placeholders and another time later for the other filters that fill the insert-Queues later. 
Perhaps the problem with the upload is also a consequence of including jQuery files twice.
Possible solutions:

- change the insert class such that it empties its queues once the content is inserted, or
- reorder the filters so that Insert is used just once, or
- do not use the insert class in the auto placeholder filter, so that we can have them at the beginning and delay the call to the insert class until the end

proposed temporary workaround:
- disable the insert filter

**Comment by mrbaseman** [comment] 2019-03-22 20:15
this is fixed by https://github.com/WBCE/WBCE_CMS/commit/551bc7e1b378e1e97e4b4c0e46c6ea7e394743c4

I have verified that both, the upload problem and the multiply inserted lines were caused by the additional call to doFilter() in the insert class. By setting the instance to NULL we throw away everything that has been pushed to the queues, so when the insert class is used subsequently, it behaves as if it was used for the first time on the current page

**Closed by mrbaseman** 2019-03-22 20:15 UTC
Labels: bug
