### ISSUE TITLE
[1.3 alpha2] OPF drops warnings in FE & BE

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#295] opened 2017-08-27 10:52 UTC
When PHP warnings are enabled, the following warnings occur in frontend/backend

Backend:
<b>Notice</b>:  Use of undefined constant OPF_DROPLETS_BE - assumed 'OPF_DROPLETS_BE' in <b>/.../modules/output_filter/filter_routines.php</b> on line <b>131</b><br />
<b>Notice</b>:  Use of undefined constant OPF_AUTO_PLACEHOLDER_BE - assumed 'OPF_AUTO_PLACEHOLDER_BE' in <b>/.../modules/output_filter/filter_routines.php</b> on line <b>140</b><br />
<b>Notice</b>:  Use of undefined constant OPF_MOVE_STUFF_BE - assumed 'OPF_MOVE_STUFF_BE' in <b>/.../modules/output_filter/filter_routines.php</b> on line <b>149</b><br />
<b>Notice</b>:  Use of undefined constant OPF_REPLACE_STUFF_BE - assumed 'OPF_REPLACE_STUFF_BE' in <b>/.../modules/output_filter/filter_routines.php</b> on line <b>158</b><br />
<b>Notice</b>:  Use of undefined constant OPF_CSS_TO_HEAD_BE - assumed 'OPF_CSS_TO_HEAD_BE' in <b>/.../modules/output_filter/filter_routines.php</b> on line <b>168</b><br />

**Furthermore, the backend is no more usable because of this!**

frontend:

Notice: Use of undefined constant OPF_DROPLETS - assumed 'OPF_DROPLETS' in /.../modules/output_filter/filter_routines.php on line 31
Notice: Use of undefined constant OPF_AUTO_PLACEHOLDER - assumed 'OPF_AUTO_PLACEHOLDER' in /.../modules/output_filter/filter_routines.php on line 40
Notice: Use of undefined constant OPF_MOVE_STUFF - assumed 'OPF_MOVE_STUFF' in /.../modules/output_filter/filter_routines.php on line 49
Notice: Use of undefined constant OPF_REPLACE_STUFF - assumed 'OPF_REPLACE_STUFF' in /.../modules/output_filter/filter_routines.php on line 57
Notice: Use of undefined constant OPF_CSS_TO_HEAD - assumed 'OPF_CSS_TO_HEAD' in /.../modules/output_filter/filter_routines.php on line 64
Notice: Use of undefined constant OPF_MAILTO_FILTER - assumed 'OPF_MAILTO_FILTER' in /.../modules/output_filter/filter_routines.php on line 73
Notice: Use of undefined constant OPF_MAILTO_FILTER - assumed 'OPF_MAILTO_FILTER' in /.../modules/output_filter/filters/filterEmail.php on line 18
Notice: Use of undefined constant OPF_JS_MAILTO - assumed 'OPF_JS_MAILTO' in /.../modules/output_filter/filters/filterEmail.php on line 18
Notice: Use of undefined constant OPF_WBLINK - assumed 'OPF_WBLINK' in /.../modules/output_filter/filter_routines.php on line 81
Notice: Use of undefined constant OPF_SHORT_URL - assumed 'OPF_SHORT_URL' in /.../modules/output_filter/filter_routines.php on line 90
Notice: Use of undefined constant OPF_SYS_REL - assumed 'OPF_SYS_REL' in /.../modules/output_filter/filter_routines.php on line 98

PHP 5.6, updated site from 1.1.11 to 1.3a2

On another site, the upper notices did not shine up, but:
Warning: is_readable() [function.is-readable]: open_basedir restriction in effect. File(/users/sitename/wwwmodules/outputfilter_dashboard/functions.php) is not within the allowed path(s): (/users/sitename/www:/users/_temp/sitename) in /users/sitename/www/index.php on line 89

...maybe there is a slash missing ("wwwmodules/")

**Comment by NorHei** [comment] 2017-08-27 17:23
Cannot reproduce , where can i take a look ?

**Comment by NorHei** [comment] 2017-08-27 17:23
Upgrade script run ?

**Comment by instantflorian** [comment] 2017-08-27 17:32
Alright, the update script has to be run __twice__ if this problem 
appears (I surely ran it first, other wise I would not be able to 
login), because after I copied the /install folder again onto the server 
and ran the update script agai the error messages were gone.

**Comment by NorHei** [comment] 2017-08-27 19:02
seems that the module upgrade.php script was not run properly for some reason , as its responsible for setting the settings... 

We schould keep this open , and look if it appears more often.

**Comment by instantflorian** [comment] 2017-08-27 19:21
Sorry for confusion. It's all a bit new to me.

So I understand now basically the concept. Correction: Switching off the placeholder removes 
< ! --(PH) CSS HEAD TOP+ -->
< ! --(PH) CSS HEAD TOP- -->

< ! --(PH) JS HEAD TOP+ -->
< ! --(PH) JS HEAD TOP- -->
Whether the appears is dependant on the template. In a simple self-build template these lines appear, in vertal they don't.

So I thought, switching off Meta insert by modules removes 
< ! --(PH) TITLE+ -->
but this is not the case.

**Comment by Colinax** [comment] 2017-09-04 13:54
should be fixed with  ad42f3b

**Closed by Colinax** 2017-09-04 13:54 UTC
Labels: bug
